"""Add advanced telemetry models

Revision ID: 5ba7096f2bf8
Revises: 79417bd8e7a9
Create Date: 2026-05-28 20:20:23.832570
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '5ba7096f2bf8'
down_revision: Union[str, None] = '79417bd8e7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency_reputation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('ecosystem', sa.String(length=50), nullable=False),
    sa.Column('is_hallucinated', sa.Boolean(), nullable=True),
    sa.Column('is_malicious', sa.Boolean(), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dependency_reputation'))
    )
    op.create_index(op.f('ix_dependency_reputation_package_name'), 'dependency_reputation', ['package_name'], unique=False)
    op.create_table('multimodal_threats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_event_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('media_hash', sa.String(length=128), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('steganography_confidence', sa.Float(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('threat_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_event_id'], ['scan_events.id'], name=op.f('fk_multimodal_threats_scan_event_id_scan_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_multimodal_threats'))
    )
    op.create_index(op.f('ix_multimodal_threats_media_hash'), 'multimodal_threats', ['media_hash'], unique=False)
    op.create_index(op.f('ix_multimodal_threats_scan_event_id'), 'multimodal_threats', ['scan_event_id'], unique=False)
    op.create_table('rag_trust_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_event_id', sa.UUID(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('sanitized_content', sa.Text(), nullable=True),
    sa.Column('detected_injections', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_event_id'], ['scan_events.id'], name=op.f('fk_rag_trust_scores_scan_event_id_scan_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_trust_scores'))
    )
    op.create_index(op.f('ix_rag_trust_scores_scan_event_id'), 'rag_trust_scores', ['scan_event_id'], unique=False)
    op.create_table('token_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_event_id', sa.UUID(), nullable=False),
    sa.Column('estimated_complexity', sa.Float(), nullable=True),
    sa.Column('dos_risk_score', sa.Float(), nullable=True),
    sa.Column('is_recursive_loop', sa.Boolean(), nullable=True),
    sa.Column('budget_exceeded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scan_event_id'], ['scan_events.id'], name=op.f('fk_token_analytics_scan_event_id_scan_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_analytics')),
    sa.UniqueConstraint('scan_event_id', name=op.f('uq_token_analytics_scan_event_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_analytics')
    op.drop_index(op.f('ix_rag_trust_scores_scan_event_id'), table_name='rag_trust_scores')
    op.drop_table('rag_trust_scores')
    op.drop_index(op.f('ix_multimodal_threats_scan_event_id'), table_name='multimodal_threats')
    op.drop_index(op.f('ix_multimodal_threats_media_hash'), table_name='multimodal_threats')
    op.drop_table('multimodal_threats')
    op.drop_index(op.f('ix_dependency_reputation_package_name'), table_name='dependency_reputation')
    op.drop_table('dependency_reputation')
    # ### end Alembic commands ###
