"""Add subscription fields to organization

Revision ID: 79417bd8e7a9
Revises: 001_initial
Create Date: 2026-05-28 15:20:51.041203
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers
revision: str = '79417bd8e7a9'
down_revision: str | None = '001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('subscription_status', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('subscription_interval', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('threat_signatures', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threat_signatures', 'embedding')
    op.drop_column('organizations', 'subscription_end_date')
    op.drop_column('organizations', 'subscription_interval')
    op.drop_column('organizations', 'subscription_status')
    # ### end Alembic commands ###
