"use client";

import { motion } from "framer-motion";
import {
  Image as ImageIcon, Globe2, FileText, PackageX, ZapOff, ShieldAlert,
  Fingerprint, Flame, Brain, BookLock, Type, Wifi,
} from "lucide-react";

const ADVANCED_FEATURES = [
  { icon: ImageIcon, title: "Multimodal Threat Defense", description: "Scan images, audio, PDFs, and media payloads in real-time for steganography, OCR-extracted prompt injections, and hidden visual/audio instructions.", color: "from-red-500 to-rose-600" },
  { icon: FileText, title: "RAG Context Sandbox", description: "Automatically inspect and sanitize untrusted external documents, HTML, and vector DB chunks before they are ingested by the LLM.", color: "from-amber-500 to-orange-600" },
  { icon: PackageX, title: "Supply Chain Validation", description: "Intercept hallucinatory dependencies (e.g., fake npm or PyPI packages) generated by your AI to prevent zero-day supply chain compromises.", color: "from-blue-500 to-cyan-600" },
  { icon: Globe2, title: "Cross-Lingual Inference", description: "Detect translated jailbreaks, Swahili DAN attacks, and mixed-language instruction overrides using multi-lingual embedding classifiers.", color: "from-emerald-500 to-teal-600" },
  { icon: ShieldAlert, title: "Exotic Encoding Chains", description: "Recursively decode and inspect payloads hidden in Base85, Morse code, ROT13, custom ciphers, and nested emoji obfuscations.", color: "from-cyan-500 to-blue-600" },
  { icon: ZapOff, title: "LLM DoS Prevention", description: "Predict token complexity, block recursive instruction loops, and prevent pathological token explosion attacks from bankrupting your API budget.", color: "from-yellow-500 to-amber-600" },
  { icon: Fingerprint, title: "Oracle Attack Shield", description: "Detect model inversion and weight-stealing attacks via behavioral pattern analysis — query velocity monitoring, logprob fishing detection, and semantic clustering across sessions.", color: "from-indigo-500 to-blue-600" },
  { icon: Flame, title: "Sponge DoS Protection", description: "Block adversarial token sequences that exploit O(n²) Transformer attention complexity to cause GPU compute exhaustion. Enforces per-session compute budgets.", color: "from-rose-500 to-red-600" },
  { icon: Brain, title: "Business Logic Guard", description: "Validates intent behind destructive tool calls with scope-creep detection, urgency framing analysis, and human-in-the-loop gates for irreversible operations.", color: "from-sky-500 to-blue-600" },
  { icon: BookLock, title: "Memorization Leak Blocker", description: "Detects training data exfiltration via repetition triggers, divergence patterns, and verbatim reproduction attacks. Scans outputs for proprietary code leaks.", color: "from-violet-500 to-indigo-600" },
  { icon: Type, title: "Tokenizer Shield", description: "Blocks zero-day Unicode and tokenizer-splitting attacks: BiDi overrides, zero-width injection, homoglyph substitution, and Private Use Area character abuse.", color: "from-teal-500 to-cyan-600" },
  { icon: Wifi, title: "Out-of-Band Defender", description: "Inspects all externally retrieved content — web pages, emails, documents — before LLM injection. Detects white-on-white hidden text, HTML injection vectors, and tracks source reputation.", color: "from-orange-500 to-amber-600" },
];

const cardVariants = {
  hidden: { opacity: 0, y: 50, scale: 0.95, filter: 'blur(8px)' },
  visible: (i: number) => ({
    opacity: 1, y: 0, scale: 1, filter: 'blur(0px)',
    transition: { duration: 0.6, delay: i * 0.06, ease: [0.16, 1, 0.3, 1] },
  }),
};

const iconFloat = {
  rest: { y: 0, rotate: 0 },
  hover: { y: -4, rotate: -6, transition: { type: 'spring', stiffness: 400, damping: 15 } },
};

export default function AdvancedFeatures() {
  return (
    <section className="py-24 px-6 relative z-10 border-t border-white/5 bg-transparent">
      <div className="max-w-7xl mx-auto">
        {/* Section header with cinematic entrance */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
          className="text-center mb-16"
        >
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-red-500/10 border border-red-500/20 mb-4">
            <motion.span
              animate={{ scale: [1, 1.3, 1], opacity: [1, 0.6, 1] }}
              transition={{ duration: 2, repeat: Infinity }}
              className="w-2 h-2 rounded-full bg-red-400"
            />
            <span className="text-xs font-semibold text-red-400 uppercase tracking-wider">Advanced Enterprise Capabilities</span>
          </div>
          <h2 className="text-3xl md:text-5xl font-bold mb-4">Unprecedented Coverage</h2>
          <p className="text-gray-400 text-lg max-w-2xl mx-auto">
            Go beyond standard text regex. Protect your AI from zero-day vectors that other firewalls ignore.
          </p>
        </motion.div>

        {/* Cards with elite stagger + 3D hover */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6" style={{ perspective: '1400px' }}>
          {ADVANCED_FEATURES.map((feature, i) => (
            <motion.div
              key={i}
              custom={i}
              variants={cardVariants}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, margin: '-40px' }}
              whileHover={{ y: -6, rotateX: 2, rotateY: -1, transition: { duration: 0.3, ease: [0.16, 1, 0.3, 1] } }}
              className="enterprise-panel p-6 group relative overflow-hidden cursor-default transition-all duration-300"
              style={{ transformStyle: 'preserve-3d' }}
            >
              {/* Ambient glow orb */}
              <motion.div
                className={`absolute -top-12 -right-12 w-32 h-32 bg-gradient-to-br ${feature.color} rounded-full blur-[40px] pointer-events-none group-hover:opacity-30`}
                initial={{ opacity: 0.05 }}
                transition={{ duration: 0.4 }}
              />

              {/* Tech ID / Module designation */}
              <div className="flex justify-between items-start mb-6">
                <motion.div
                  className={`w-10 h-10 border border-white/10 bg-black/40 flex items-center justify-center transition-shadow duration-300 group-hover:bg-gradient-to-br group-hover:${feature.color} group-hover:border-transparent`}
                >
                  <feature.icon className="w-4 h-4 text-gray-300 group-hover:text-white transition-colors" />
                </motion.div>
                <div className="text-[9px] font-mono text-gray-500 uppercase tracking-widest group-hover:text-gray-300 transition-colors">
                  ADV_{String(i + 1).padStart(2, '0')}
                </div>
              </div>

              <h3 className="text-sm font-bold text-white mb-2 font-mono uppercase tracking-wider relative z-10 group-hover:text-white transition-colors">{feature.title}</h3>
              <p className="text-gray-400 leading-relaxed text-[13px] relative z-10">{feature.description}</p>

              {/* Bottom glow line */}
              <motion.div
                className={`absolute bottom-0 left-0 right-0 h-px bg-gradient-to-r ${feature.color}`}
                initial={{ scaleX: 0, opacity: 0 }}
                whileHover={{ scaleX: 1, opacity: 1 }}
                transition={{ duration: 0.5 }}
              />
              <div className="absolute top-0 right-0 w-2 h-2 border-t border-r border-white/10 transition-colors" />
              <div className="absolute bottom-0 left-0 w-2 h-2 border-b border-l border-white/10 transition-colors" />
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
