"""
Cross-Key Orchestration Monitor — GhostPrompt Core

System-level coordination layer that sits above individual detectors
and monitors cross-API-key correlations and system-level semantic drift.

This module provides:
  1. Cross-key request correlation (different API keys, same attack)
  2. System-level semantic trajectory monitoring
  3. Global Pack Hunt campaign aggregation
  4. Red team metrics collection
"""

import time
import hashlib
import math
from typing import Optional
from collections import defaultdict
from dataclasses import dataclass, field
from app.core.logging import get_logger

logger = get_logger("orchestration_monitor")


@dataclass
class OrchestrationAlert:
    """An alert generated by the orchestration monitor."""
    alert_id: str
    alert_type: str  # cross_key, semantic_drift, campaign_escalation
    severity: str
    description: str
    involved_keys: list[str]
    timestamp: float
    metadata: dict = field(default_factory=dict)


class OrchestrationMonitor:
    """
    Global orchestration-level security monitor.

    Operates above individual request detection to identify patterns
    that span multiple API keys, sessions, and time windows.
    """

    def __init__(self):
        self._initialized = False
        # Cross-key request tracking: content_hash -> list of (api_key, timestamp)
        self._content_fingerprints: dict[str, list[tuple[str, float]]] = defaultdict(list)
        # API key activity profiles
        self._key_profiles: dict[str, dict] = defaultdict(lambda: {
            "total_requests": 0,
            "blocked_requests": 0,
            "flagged_requests": 0,
            "first_seen": time.time(),
            "last_seen": time.time(),
            "categories_hit": defaultdict(int),
            "sessions": set(),
        })
        # Alerts
        self._alerts: list[OrchestrationAlert] = []
        # Red team metrics
        self._red_team_metrics: dict = {
            "total_attacks_tested": 0,
            "false_negatives": 0,
            "false_positives": 0,
            "last_run": None,
            "certification_status": "UNCERTIFIED",
            "certification_timestamp": None,
            "weekly_attack_count": 0,
        }
        # Certification results
        self._certification: dict = {
            "status": "UNCERTIFIED",
            "tier1_pass": False,
            "tier2_pass": False,
            "tier3_pass": False,
            "tier4_pass": False,
            "tier1_score": 0.0,
            "tier2_score": 0.0,
            "tier3_score": 0.0,
            "tier4_score": 0.0,
            "last_run": None,
        }

    async def initialize(self):
        if self._initialized:
            return
        logger.info("orchestration_monitor_initialized")
        self._initialized = True

    def track_request(
        self,
        api_key: str,
        text: str,
        session_id: str = "",
        action: str = "allowed",
        threat_categories: list[str] = None,
    ):
        """Track a request for cross-key correlation."""
        now = time.time()

        # Content fingerprint for cross-key detection
        content_hash = hashlib.sha256(text.lower().strip().encode()).hexdigest()[:32]
        self._content_fingerprints[content_hash].append((api_key, now))

        # Prune old fingerprints (older than 2 hours)
        cutoff = now - 7200
        for h in list(self._content_fingerprints.keys()):
            self._content_fingerprints[h] = [
                (k, t) for k, t in self._content_fingerprints[h] if t > cutoff
            ]
            if not self._content_fingerprints[h]:
                del self._content_fingerprints[h]

        # Update key profile
        profile = self._key_profiles[api_key]
        profile["total_requests"] += 1
        profile["last_seen"] = now
        if session_id:
            profile["sessions"].add(session_id)
        if action == "blocked":
            profile["blocked_requests"] += 1
        elif action == "flagged":
            profile["flagged_requests"] += 1
        for cat in (threat_categories or []):
            profile["categories_hit"][cat] += 1

        # Check for cross-key duplicate content
        key_set = set(k for k, _ in self._content_fingerprints.get(content_hash, []))
        if len(key_set) > 1:
            alert = OrchestrationAlert(
                alert_id=hashlib.sha256(f"{content_hash}{now}".encode()).hexdigest()[:16],
                alert_type="cross_key_duplicate",
                severity="high",
                description=(
                    f"Same content submitted from {len(key_set)} different API keys within 2 hours. "
                    f"Possible coordinated attack or distributed Pack Hunt."
                ),
                involved_keys=list(key_set),
                timestamp=now,
                metadata={"content_hash": content_hash},
            )
            self._alerts.append(alert)
            logger.warning("cross_key_duplicate_detected", keys=len(key_set), hash=content_hash)

    def update_red_team_metrics(self, metrics: dict):
        """Update red team metrics from automated testing."""
        self._red_team_metrics.update(metrics)
        self._red_team_metrics["last_run"] = time.time()

    def update_certification(self, results: dict):
        """Update certification status."""
        self._certification.update(results)
        self._certification["last_run"] = time.time()

        # Determine overall status
        if results.get("tier1_pass") and results.get("tier2_pass") and results.get("tier3_pass") and results.get("tier4_pass"):
            self._certification["status"] = "CERTIFIED_SECURE"
        elif results.get("tier1_pass") and results.get("tier2_pass"):
            self._certification["status"] = "PARTIAL"
        else:
            self._certification["status"] = "UNCERTIFIED"

    def get_certification_status(self) -> dict:
        """Get current certification status for display."""
        return dict(self._certification)

    def get_red_team_metrics(self) -> dict:
        """Get current red team metrics."""
        return dict(self._red_team_metrics)

    def get_alerts(self, limit: int = 50) -> list[dict]:
        """Get recent orchestration alerts."""
        return [
            {
                "alert_id": a.alert_id,
                "alert_type": a.alert_type,
                "severity": a.severity,
                "description": a.description,
                "involved_keys": [k[:8] + "..." for k in a.involved_keys],
                "timestamp": a.timestamp,
                "metadata": a.metadata,
            }
            for a in self._alerts[-limit:]
        ]

    def get_stats(self) -> dict:
        """Get orchestration monitor statistics."""
        return {
            "tracked_api_keys": len(self._key_profiles),
            "content_fingerprints": len(self._content_fingerprints),
            "total_alerts": len(self._alerts),
            "certification": self._certification["status"],
            "red_team_weekly_attacks": self._red_team_metrics.get("weekly_attack_count", 0),
        }


# Singleton
orchestration_monitor = OrchestrationMonitor()
